source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '12.0'

target 'KKDownload_Example' do
  pod 'KKDownload', :path => '../'

  target 'KKDownload_Tests' do
    inherit! :search_paths

    
  end
end
