source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '12.0'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
 end
end

target 'KKDownload_Example' do
  pod 'KKDownload', :path => '../'

  pod 'AFNetworking'
  pod 'YYModel'
  
  target 'KKDownload_Tests' do
    inherit! :search_paths
    
  end
end
